---
title: "5_PCA"
output: html_document
---

#import RDS
```{r}
w_merge_n<-readRDS(file.path("raw_data","RDS","wheat_annota.rds"))
c_merge_n<-readRDS(file.path("raw_data","RDS","corn_annota.rds"))
s_merge_n<-readRDS(file.path("raw_data","RDS","soybean_annota.rds"))
b_merge_n<-readRDS(file.path("raw_data","RDS","bean_annota.rds"))
```

#combining count data
```{r}
####Step1 - remove any "miRNA" that have counts in no_plant####
w_merge_n <- w_merge_n %>%
  group_by(mature_miRNA) %>%
  filter(!any(Sp == "ctl" & count > 0)) %>%
  ungroup()
c_merge_n <- c_merge_n %>%
  group_by(mature_miRNA) %>%
  filter(!any(Sp == "ctl" & count > 0)) %>%
  ungroup()
s_merge_n <- s_merge_n %>%
  group_by(mature_miRNA) %>%
  filter(!any(Sp == "ctl" & count > 0)) %>%
  ungroup()
b_merge_n <- b_merge_n %>%
  group_by(mature_miRNA) %>%
  filter(!any(Sp == "ctl" & count > 0)) %>%
  ungroup()
#manually check the non annotated sequences(just the one asbent in no plant )
#for the unknown miRNA, manually check by blast and determine if relevant
#wheat
#AACGAGUUCCAGACGAUGCAGG 32.2	32.2	91%	1.2	95.00%	rm
#ACGAGUUCCAGACGAUGCAGG 	32.2	32.2	95%	1.0	95.00% rm
#CCAUGGCCAAGGUCUCGUGAGG 36.2	36.2	100%	0.080	95.45% #idk, on the fence, I think will rm
#CCGUGGCCAAGGUCUCUUGAGG 44.1	44.1	100%	3e-04	100.00%	 keep
#GCGAGUUUCAGAUGAUGCAGG 34.2	34.2	100%	0.26	95.24% probably rm (match disease resistance protein Pik2 like most others
#apparently pik belong to NLR family which are near TE rich region (very abundant in wheat), so maybe these are phasiRNA...
#now removing them
to_remove <- c("AACGAGUUCCAGACGAUGCAGG","ACGAGUUCCAGACGAUGCAGG", "CCAUGGCCAAGGUCUCGUGAGG", "GCGAGUUUCAGAUGAUGCAGG")
w_merge_n <- w_merge_n %>%
  filter(!mature_miRNA %in% to_remove)
#corn : nothing
#soybean
#UGUCCAAUCCAUAGUUUUAAAG Select seq NR_126642.1	Glycine max microRNA MIR5770b (MIR5770B), microRNA	Glycine max	44.1	66.4	100%	9e-05	100.00%	keep, might be miRN. Checked and it match MIR5770b stem loop
#GAGCUCUCUGCACUCCAGUGU Glycine max microRNA MIR156aa (MIR156AA), microRNA	Glycine max	42.1	42.1	100%	4e-04	100.00%

#so both of them match precursor. Looking at the precusor, only 1 mature miRNA is present
#both of these are at the opposite (my MIR5770b at 3' and MIR156aa at 5' )
#therefore I am going to manually anotate them
s_merge_n$mir_id[s_merge_n$mature_miRNA == "UGUCCAAUCCAUAGUUUUAAAG"] <- "putative gma-miR5770b*"
s_merge_n$mir_id[s_merge_n$mature_miRNA == "GAGCUCUCUGCACUCCAGUGU"] <- "putative gma-miR156aa*"
#missed GAGCUCUCAGCACUCCAGUGU, gma-MIR156z. Very simialr to 156aa, also at 5'
s_merge_n$mir_id[s_merge_n$mature_miRNA == "GAGCUCUCAGCACUCCAGUGU"] <- "putative gma-miR156z*"
#bean : nothing

####Step2 - remove all no plant from each df####
wheat_p <- w_merge_n[w_merge_n$Sp != "ctl", ]
corn_p <- c_merge_n[c_merge_n$Sp != "ctl", ]
soybean_p <- s_merge_n[s_merge_n$Sp != "ctl", ]
bean_p <- b_merge_n[b_merge_n$Sp != "ctl", ]
####Step3 - merge####
Combi <- rbind(wheat_p, corn_p, soybean_p, bean_p)

#make ASV/OTU number (ex miR_1, 2...)
# Rank sequences by total abundance
mir_x <- Combi %>%
  group_by(mature_miRNA) %>%
  summarise(total_count = sum(count), .groups = "drop") %>%
  arrange(desc(total_count)) %>%
  mutate(miR_X = paste0("miR_", row_number()))
Combi <- Combi %>%
  left_join(mir_x %>% select(mature_miRNA, miR_X),
            by = "mature_miRNA")
Combi <- Combi %>%
  relocate(miR_X, .after = 1)
#removing any miR that have 0 total counts
Combi <- Combi %>%
  group_by(mature_miRNA) %>%
  filter(any(count != 0)) %>%
  ungroup()
saveRDS(Combi, file = here("raw_data","RDS","Combi.RDS")) 
```

#hellinger transformation
```{r}
#prep count matrix
df_wide <- Combi %>% #put it wide format. Only keep raw count
  pivot_wider(
    id_cols = c(Row.names, Plant, Sp, Water_treatment, Bloc),
    names_from = mature_miRNA,
    values_from = count,
    values_fill = 0
  )
df_wide <- as.data.frame(df_wide)
row.names(df_wide) <- df_wide$Row.names
df_wide$Row.names <- NULL
df_count <- df_wide %>% select(5:55)
matrix <- as.matrix(df_count)
matrix_clean <- matrix[rowSums(matrix) > 0, ] #removing any samples with 0 total
metadata <- df_wide %>% select(1:4)
#if(taxa_are_rows(ps.filtered)) otu_mat <- t(otu_mat) #transpose
otu_hel <- decostand(matrix_clean, method = "hellinger")
metadata <- metadata[match(rownames(otu_hel), rownames(metadata)), ] #match nb of rows
#hellinger transform data to euclidean and gives low weight to rare ASV
```

#Permanova
```{r}
#perform permanova. To respect exchangeability, we must only perform permutation within blocks
set.seed(111)
adonis_res <- adonis2(otu_hel ~ Plant*Water_treatment, data = metadata, method = "euclidean", by = "terms", permutations = how(nperm = 9999,blocks = metadata$Bloc))#by terms for each factor + interaction
print(adonis_res)
#convert to df
results_df <- as.data.frame(adonis_res)
#export
write.csv(results_df, file = here("Output","adonis_results.csv"))
```

#PCA
```{r}
#module 13 QCBS workshop 
pca.16S<-rda (otu_hel) #performing PCA using rda (with no explicative variable)
summary(pca.16S)#see all PC and eigenvalues (which is variance?)
#broken stick model 
#The broken-stick model retains components that explain more variance than would be expected by randomly dividing the variance into 
screeplot(pca.16S, bstick = TRUE, type = "lines")#PC1 - PC4 above the red line (not the others)
#Extract Principle components
ii_16S_plantexp<-summary(pca.16S)
scale1_16S_plantexp<-scores(pca.16S, choices = 1:2, scaling=1)
#compiling site scores (scaling 1) 
stmat1_16S_plantexp<-as.data.frame(scale1_16S_plantexp$sites)
stmat1en_16S_plantexp<-cbind(Row.Names = rownames(stmat1_16S_plantexp), stmat1_16S_plantexp)
#Preparing data frame for ordination
#Here we need to join our explanatory variables and our principle components
df_16S_plantexp<- merge(stmat1en_16S_plantexp, metadata,by = 'row.names') #DF_ordi
#df_16S_plantexp$'time' <- paste(df$Compartment,df$Plant ) #  obs.  variables

#to put in order:
df_16S_plantexp$Plant <- factor(
  df_16S_plantexp$Plant,
  levels = c("walton", "red", "art", "gold", "envy","manitoba","roq", "bognol" )  # your desired order
)
df_16S_plantexp$Water_treatment <- as.factor(df_16S_plantexp$Water_treatment )
pca<-ggplot() +
  geom_point(data = df_16S_plantexp,aes(PC1,PC2,fill=Plant, shape=Water_treatment), color="grey",size=5, stroke=1)+
  scale_fill_manual(values = c("#a4161a","#ee4266","#ffbf69","#fff3b0","#d0f4de","#3dccc7","#a9def9","#1F6D99"))+
  scale_shape_manual(values=c(21,24))+
  labs(x=paste("PC1 (", format(100 *ii_16S_plantexp$cont[[1]][2,1], digits=4), "%)", sep=""),
       y=paste("PC2 (", format(100 *ii_16S_plantexp$cont[[1]][2,2], digits=4), "%)", sep=""))+
  guides(shape=guide_legend(title="WHC"))+
  guides(fill = guide_legend(title="Plant",override.aes = list(shape = 21)))+
theme_classic()
pca

ggsave(pca, file = here ("Output","Pca.png"), width = 18, height = 15, units = "cm")
```

```{r}
#PC2 and 3
scale1_16S_plantexp<-scores(pca.16S, choices = 2:3, scaling=1)
#compiling site scores (scaling 1) 
stmat1_16S_plantexp<-as.data.frame(scale1_16S_plantexp$sites)
stmat1en_16S_plantexp<-cbind(Row.Names = rownames(stmat1_16S_plantexp), stmat1_16S_plantexp)
#Preparing data frame for ordination
#Here we need to join our explanatory variables and our principle components
df_16S_plantexp<- merge(stmat1en_16S_plantexp, metadata,by = 'row.names') #DF_ordi
#df_16S_plantexp$'time' <- paste(df$Compartment,df$Plant ) #  obs.  variables

#to put in order:
df_16S_plantexp$Plant <- factor(
  df_16S_plantexp$Plant,
  levels = c("walton", "red", "art", "gold", "envy","manitoba","roq", "bognol" )  # your desired order
)
df_16S_plantexp$Water_treatment <- as.factor(df_16S_plantexp$Water_treatment )
pca<-ggplot() +
  geom_point(data = df_16S_plantexp,aes(PC2,PC3,fill=Plant, shape=Water_treatment), color="grey",size=5, stroke=1)+
  scale_fill_manual(values = c("#a4161a","#ee4266","#ffbf69","#fff3b0","#d0f4de","#3dccc7","#a9def9","#1F6D99"))+
  scale_shape_manual(values=c(21,24))+
  labs(x=paste("PC2 (", format(100 *ii_16S_plantexp$cont[[1]][2,2], digits=4), "%)", sep=""),
       y=paste("PC3 (", format(100 *ii_16S_plantexp$cont[[1]][2,3], digits=4), "%)", sep=""))+
  guides(shape=guide_legend(title="WHC"))+
  guides(fill = guide_legend(title="Plant",override.aes = list(shape = 21)))+
theme_classic()
pca


#PC3 and 4
scale1_16S_plantexp<-scores(pca.16S, choices = 3:4, scaling=1)
#compiling site scores (scaling 1) 
stmat1_16S_plantexp<-as.data.frame(scale1_16S_plantexp$sites)
stmat1en_16S_plantexp<-cbind(Row.Names = rownames(stmat1_16S_plantexp), stmat1_16S_plantexp)
#Preparing data frame for ordination
#Here we need to join our explanatory variables and our principle components
df_16S_plantexp<- merge(stmat1en_16S_plantexp, metadata,by = 'row.names') #DF_ordi
#df_16S_plantexp$'time' <- paste(df$Compartment,df$Plant ) #  obs.  variables

#to put in order:
df_16S_plantexp$Plant <- factor(
  df_16S_plantexp$Plant,
  levels = c("walton", "red", "art", "gold", "envy","manitoba","roq", "bognol" )  # your desired order
)
df_16S_plantexp$Water_treatment <- as.factor(df_16S_plantexp$Water_treatment )
pca<-ggplot() +
  geom_point(data = df_16S_plantexp,aes(PC3,PC4,fill=Plant, shape=Water_treatment), color="grey",size=5, stroke=1)+
  scale_fill_manual(values = c("#a4161a","#ee4266","#ffbf69","#fff3b0","#d0f4de","#3dccc7","#a9def9","#1F6D99"))+
  scale_shape_manual(values=c(21,24))+
  labs(x=paste("PC3 (", format(100 *ii_16S_plantexp$cont[[1]][2,3], digits=4), "%)", sep=""),
       y=paste("PC4 (", format(100 *ii_16S_plantexp$cont[[1]][2,], digits=4), "%)", sep=""))+
  guides(shape=guide_legend(title="WHC"))+
  guides(fill = guide_legend(title="Plant",override.aes = list(shape = 21)))+
theme_classic()
pca

#1 and 3
scale1_16S_plantexp<-scores(pca.16S, choices = 1:3, scaling=1)
#compiling site scores (scaling 1) 
stmat1_16S_plantexp<-as.data.frame(scale1_16S_plantexp$sites)
stmat1en_16S_plantexp<-cbind(Row.Names = rownames(stmat1_16S_plantexp), stmat1_16S_plantexp)
#Preparing data frame for ordination
#Here we need to join our explanatory variables and our principle components
df_16S_plantexp<- merge(stmat1en_16S_plantexp, metadata,by = 'row.names') #DF_ordi
#df_16S_plantexp$'time' <- paste(df$Compartment,df$Plant ) #  obs.  variables

#to put in order:
df_16S_plantexp$Plant <- factor(
  df_16S_plantexp$Plant,
  levels = c("walton", "red", "art", "gold", "envy","manitoba","roq", "bognol" )  # your desired order
)
df_16S_plantexp$Water_treatment <- as.factor(df_16S_plantexp$Water_treatment )
pca<-ggplot() +
  geom_point(data = df_16S_plantexp,aes(PC1,PC3,fill=Plant, shape=Water_treatment), color="grey",size=5, stroke=1)+
  scale_fill_manual(values = c("#a4161a","#ee4266","#ffbf69","#fff3b0","#d0f4de","#3dccc7","#a9def9","#1F6D99"))+
  scale_shape_manual(values=c(21,24))+
  labs(x=paste("PC1 (", format(100 *ii_16S_plantexp$cont[[1]][2,1], digits=4), "%)", sep=""),
       y=paste("PC3 (", format(100 *ii_16S_plantexp$cont[[1]][2,3], digits=4), "%)", sep=""))+
  guides(shape=guide_legend(title="WHC"))+
  guides(fill = guide_legend(title="Plant",override.aes = list(shape = 21)))+
theme_classic()
pca

```


#redo without 15%
```{r}
Combi_50<-Combi[Combi$Water_treatment != "15",]
#prep count matrix
df_wide <- Combi_50 %>% #put it wide format. Only keep raw count
  pivot_wider(
    id_cols = c(Row.names, Plant, Sp, Bloc),
    names_from = mature_miRNA,
    values_from = count,
    values_fill = 0
  )
df_wide <- as.data.frame(df_wide)
row.names(df_wide) <- df_wide$Row.names
df_wide$Row.names <- NULL
df_count <- df_wide %>% select(4:57)
matrix <- as.matrix(df_count)
matrix_clean <- matrix[rowSums(matrix) > 0, ] #removing any samples with 0 total
metadata <- df_wide %>% select(1:3)
#if(taxa_are_rows(ps.filtered)) otu_mat <- t(otu_mat) #transpose
otu_hel <- decostand(matrix_clean, method = "hellinger")
metadata <- metadata[match(rownames(otu_hel), rownames(metadata)), ] #match nb of rows
#hellinger transform data to euclidean and gives low weight to rare ASV

#perform permanova. To respect exchangeability, we must only perform permutation within blocks
set.seed(111)
adonis_res <- adonis2(otu_hel ~ Plant, data = metadata, method = "euclidean", by = "terms", permutations = how(nperm = 9999,blocks = metadata$Bloc))#by terms for each factor + interaction
print(adonis_res)
#convert to df
results_df <- as.data.frame(adonis_res)
#export
#write.csv(results_df, file = here("Output","adonis_results.csv"))


#module 13 QCBS workshop 
pca.16S<-rda (otu_hel) #performing PCA using rda (with no explicative variable)
summary(pca.16S)#see all PC and eigenvalues (which is variance?)
#broken stick model 
#The broken-stick model retains components that explain more variance than would be expected by randomly dividing the variance into 
screeplot(pca.16S, bstick = TRUE, type = "lines")#PC1 - PC4 above the red line (not the others)
#Extract Principle components
ii_16S_plantexp<-summary(pca.16S)
scale1_16S_plantexp<-scores(pca.16S, choices = 1:2, scaling=1)
#compiling site scores (scaling 1) 
stmat1_16S_plantexp<-as.data.frame(scale1_16S_plantexp$sites)
stmat1en_16S_plantexp<-cbind(Row.Names = rownames(stmat1_16S_plantexp), stmat1_16S_plantexp)
#Preparing data frame for ordination
#Here we need to join our explanatory variables and our principle components
df_16S_plantexp<- merge(stmat1en_16S_plantexp, metadata,by = 'row.names') #DF_ordi
#df_16S_plantexp$'time' <- paste(df$Compartment,df$Plant ) #  obs.  variables

#to put in order:
df_16S_plantexp$Plant <- factor(
  df_16S_plantexp$Plant,
  levels = c("walton", "red", "art", "gold", "envy","manitoba","roq", "bognol" )  # your desired order
)

pca<-ggplot() +
  geom_point(data = df_16S_plantexp,aes(PC1,PC2,fill=Plant), color="grey", shape = 21, size=5, stroke=1)+
  scale_fill_manual(values = c("#a4161a","#ee4266","#ffbf69","#fff3b0","#d0f4de","#3dccc7","#a9def9","#1F6D99"))+
  labs(x=paste("PC1 (", format(100 *ii_16S_plantexp$cont[[1]][2,1], digits=4), "%)", sep=""),
       y=paste("PC2 (", format(100 *ii_16S_plantexp$cont[[1]][2,2], digits=4), "%)", sep=""))+
  guides(fill = guide_legend(title="Plant",override.aes = list(shape = 21)))+
theme_classic()
pca

#ggsave(pca, file = here ("Output","Pca.png"), width = 18, height = 15, units = "cm")

```


#redo with only wheat
```{r}
Wheat<-Combi[Combi$Sp == "wheat",]
#prep count matrix
df_wide <- Wheat %>% #put it wide format. Only keep raw count
  pivot_wider(
    id_cols = c(Row.names, Plant, Sp,Water_treatment, Bloc),
    names_from = mature_miRNA,
    values_from = count,
    values_fill = 0
  )
df_wide <- as.data.frame(df_wide)
row.names(df_wide) <- df_wide$Row.names
df_wide$Row.names <- NULL
df_count <- df_wide %>% select(5:22)
matrix <- as.matrix(df_count)
matrix_clean <- matrix[rowSums(matrix) > 0, ] #removing any samples with 0 total
metadata <- df_wide %>% select(1:4)
#if(taxa_are_rows(ps.filtered)) otu_mat <- t(otu_mat) #transpose
otu_hel <- decostand(matrix_clean, method = "hellinger")
metadata <- metadata[match(rownames(otu_hel), rownames(metadata)), ] #match nb of rows
#hellinger transform data to euclidean and gives low weight to rare ASV

#perform permanova. To respect exchangeability, we must only perform permutation within blocks
set.seed(111)
adonis_res <- adonis2(otu_hel ~ Plant*Water_treatment, data = metadata, method = "euclidean", by = "terms", permutations = how(nperm = 9999,blocks = metadata$Bloc))#by terms for each factor + interaction
print(adonis_res)
#convert to df
results_df <- as.data.frame(adonis_res)
#export
#write.csv(results_df, file = here("Output","adonis_results.csv"))


#module 13 QCBS workshop 
pca.16S<-rda (otu_hel) #performing PCA using rda (with no explicative variable)
summary(pca.16S)#see all PC and eigenvalues (which is variance?)
#broken stick model 
#The broken-stick model retains components that explain more variance than would be expected by randomly dividing the variance into 
screeplot(pca.16S, bstick = TRUE, type = "lines")#PC1 - PC4 above the red line (not the others)
#Extract Principle components
ii_16S_plantexp<-summary(pca.16S)
scale1_16S_plantexp<-scores(pca.16S, choices = 1:2, scaling=1)
#compiling site scores (scaling 1) 
stmat1_16S_plantexp<-as.data.frame(scale1_16S_plantexp$sites)
stmat1en_16S_plantexp<-cbind(Row.Names = rownames(stmat1_16S_plantexp), stmat1_16S_plantexp)
#Preparing data frame for ordination
#Here we need to join our explanatory variables and our principle components
df_16S_plantexp<- merge(stmat1en_16S_plantexp, metadata,by = 'row.names') #DF_ordi
#df_16S_plantexp$'time' <- paste(df$Compartment,df$Plant ) #  obs.  variables

#to put in order:
df_16S_plantexp$Plant <- factor(
  df_16S_plantexp$Plant,
  levels = c("walton", "red") ) # your desired order
df_16S_plantexp$Water_treatment <- as.factor(df_16S_plantexp$Water_treatment )
pca_wheat<-ggplot() +
  geom_point(data = df_16S_plantexp,aes(PC1,PC2,fill=Plant, shape=Water_treatment), color="grey",size=5, stroke=1)+
  scale_fill_manual(values = c("#a4161a","#ee4266","#ffbf69","#fff3b0","#d0f4de","#3dccc7","#a9def9","#1F6D99"))+
  scale_shape_manual(values=c(21,24))+
  labs(x=paste("PC1 (", format(100 *ii_16S_plantexp$cont[[1]][2,1], digits=4), "%)", sep=""),
       y=paste("PC2 (", format(100 *ii_16S_plantexp$cont[[1]][2,2], digits=4), "%)", sep=""))+
  guides(shape=guide_legend(title="WHC"))+
  guides(fill = guide_legend(title="Plant",override.aes = list(shape = 21)))+
theme_classic()
pca_wheat

ggsave(pca_wheat, file = here ("Output","Pca_wheat.png"), width = 18, height = 15, units = "cm")

```

